export const services = [
	{
		id: 1,
		bg: '/intro/med.png',
		text: 'Медицинские услуги',
		href: '/services',
		rightSide: true,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Гинекология',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Офтальмология',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'УЗИ',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'Маммология',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Урология',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Эндокринология',
				href: '/services',
				rightSide: false,
			},
		],
	},
	{
		id: 2,
		bg: '/intro/anal.png',
		text: 'Анализы',
		href: '/services',
		rightSide: true,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Лейкоцитарная формула',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Протромбин, МНО',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'Протеин C',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'D-Димер',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Глюкоза',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Лактат',
				href: '/services',
				rightSide: false,
			},
		],
	},
	{
		id: 3,
		bg: '/intro/stoma.png',
		text: 'Стоматология',
		href: '/services',
		rightSide: true,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Общие работы',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Терапия',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'Имплантология',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'Пародонтология',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Протезирование',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Вениры',
				href: '/services',
				rightSide: false,
			},
		],
	},
	{
		id: 4,
		bg: '/intro/pills.png',
		text: 'Аптека',
		href: '/services',
		rightSide: false,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Антибактериальные препараты',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Гормоны',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'Диагностические средства',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'Иммунитет',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Tонус сосудов',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Свертываемость крови',
				href: '/services',
				rightSide: false,
			},
		],
	},
	{
		id: 5,
		bg: '/intro/rengen.png',
		text: 'Ренгенология',
		href: '/services',
		rightSide: false,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Маммография',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Пищевода, желудка',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'Мягких тканей',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'Носоглотки, гортани',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Фистулография',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Маммография',
				href: '/services',
				rightSide: false,
			},
		],
	},
	{
		id: 6,
		bg: '/intro/netradi.png',
		text: 'Нетрадиционная Медицина',
		href: '/services',
		rightSide: false,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Остеопатия',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Биохакинг',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'Натуропатия',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'Рэйки',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Аюрведа',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Магнитотерапия',
				href: '/services',
				rightSide: false,
			},
		],
	},
];
